
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const Accordion: typeof import("../components/ui/accordion/index").Accordion
export const AccordionContent: typeof import("../components/ui/accordion/index").AccordionContent
export const AccordionItem: typeof import("../components/ui/accordion/index").AccordionItem
export const AccordionTrigger: typeof import("../components/ui/accordion/index").AccordionTrigger
export const Alert: typeof import("../components/ui/alert/index").Alert
export const AlertDescription: typeof import("../components/ui/alert/index").AlertDescription
export const AlertTitle: typeof import("../components/ui/alert/index").AlertTitle
export const Avatar: typeof import("../components/ui/avatar/index").Avatar
export const AvatarFallback: typeof import("../components/ui/avatar/index").AvatarFallback
export const AvatarImage: typeof import("../components/ui/avatar/index").AvatarImage
export const Badge: typeof import("../components/ui/badge/index").Badge
export const Button: typeof import("../components/ui/button/index").Button
export const Calendar: typeof import("../components/ui/calendar/index").Calendar
export const CalendarCell: typeof import("../components/ui/calendar/index").CalendarCell
export const CalendarCellTrigger: typeof import("../components/ui/calendar/index").CalendarCellTrigger
export const CalendarGrid: typeof import("../components/ui/calendar/index").CalendarGrid
export const CalendarGridBody: typeof import("../components/ui/calendar/index").CalendarGridBody
export const CalendarGridHead: typeof import("../components/ui/calendar/index").CalendarGridHead
export const CalendarGridRow: typeof import("../components/ui/calendar/index").CalendarGridRow
export const CalendarHeadCell: typeof import("../components/ui/calendar/index").CalendarHeadCell
export const CalendarHeader: typeof import("../components/ui/calendar/index").CalendarHeader
export const CalendarHeading: typeof import("../components/ui/calendar/index").CalendarHeading
export const CalendarNextButton: typeof import("../components/ui/calendar/index").CalendarNextButton
export const CalendarPrevButton: typeof import("../components/ui/calendar/index").CalendarPrevButton
export const Checkbox: typeof import("../components/ui/checkbox/index").Checkbox
export const Combobox: typeof import("../components/ui/combobox/index").Combobox
export const ComboboxAnchor: typeof import("../components/ui/combobox/index").ComboboxAnchor
export const ComboboxEmpty: typeof import("../components/ui/combobox/index").ComboboxEmpty
export const ComboboxGroup: typeof import("../components/ui/combobox/index").ComboboxGroup
export const ComboboxInput: typeof import("../components/ui/combobox/index").ComboboxInput
export const ComboboxItem: typeof import("../components/ui/combobox/index").ComboboxItem
export const ComboboxItemIndicator: typeof import("../components/ui/combobox/index").ComboboxItemIndicator
export const ComboboxList: typeof import("../components/ui/combobox/index").ComboboxList
export const ComboboxSeparator: typeof import("../components/ui/combobox/index").ComboboxSeparator
export const ComboboxTrigger: typeof import("../components/ui/combobox/index").ComboboxTrigger
export const ComboboxViewport: typeof import("../components/ui/combobox/index").ComboboxViewport
export const Dialog: typeof import("../components/ui/dialog/index").Dialog
export const DialogClose: typeof import("../components/ui/dialog/index").DialogClose
export const DialogContent: typeof import("../components/ui/dialog/index").DialogContent
export const DialogDescription: typeof import("../components/ui/dialog/index").DialogDescription
export const DialogFooter: typeof import("../components/ui/dialog/index").DialogFooter
export const DialogHeader: typeof import("../components/ui/dialog/index").DialogHeader
export const DialogOverlay: typeof import("../components/ui/dialog/index").DialogOverlay
export const DialogScrollContent: typeof import("../components/ui/dialog/index").DialogScrollContent
export const DialogTitle: typeof import("../components/ui/dialog/index").DialogTitle
export const DialogTrigger: typeof import("../components/ui/dialog/index").DialogTrigger
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index").DropdownMenu
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index").DropdownMenuCheckboxItem
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index").DropdownMenuContent
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index").DropdownMenuGroup
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index").DropdownMenuItem
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index").DropdownMenuLabel
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index").DropdownMenuRadioGroup
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index").DropdownMenuRadioItem
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index").DropdownMenuSeparator
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index").DropdownMenuShortcut
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index").DropdownMenuSub
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index").DropdownMenuSubContent
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index").DropdownMenuSubTrigger
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index").DropdownMenuTrigger
export const InputGroup: typeof import("../components/ui/input-group/index").InputGroup
export const InputGroupAddon: typeof import("../components/ui/input-group/index").InputGroupAddon
export const InputGroupButton: typeof import("../components/ui/input-group/index").InputGroupButton
export const InputGroupInput: typeof import("../components/ui/input-group/index").InputGroupInput
export const InputGroupText: typeof import("../components/ui/input-group/index").InputGroupText
export const InputGroupTextarea: typeof import("../components/ui/input-group/index").InputGroupTextarea
export const Input: typeof import("../components/ui/input/index").Input
export const Label: typeof import("../components/ui/label/index").Label
export const Menubar: typeof import("../components/ui/menubar/index").Menubar
export const MenubarCheckboxItem: typeof import("../components/ui/menubar/index").MenubarCheckboxItem
export const MenubarContent: typeof import("../components/ui/menubar/index").MenubarContent
export const MenubarGroup: typeof import("../components/ui/menubar/index").MenubarGroup
export const MenubarItem: typeof import("../components/ui/menubar/index").MenubarItem
export const MenubarLabel: typeof import("../components/ui/menubar/index").MenubarLabel
export const MenubarMenu: typeof import("../components/ui/menubar/index").MenubarMenu
export const MenubarRadioGroup: typeof import("../components/ui/menubar/index").MenubarRadioGroup
export const MenubarRadioItem: typeof import("../components/ui/menubar/index").MenubarRadioItem
export const MenubarSeparator: typeof import("../components/ui/menubar/index").MenubarSeparator
export const MenubarShortcut: typeof import("../components/ui/menubar/index").MenubarShortcut
export const MenubarSub: typeof import("../components/ui/menubar/index").MenubarSub
export const MenubarSubContent: typeof import("../components/ui/menubar/index").MenubarSubContent
export const MenubarSubTrigger: typeof import("../components/ui/menubar/index").MenubarSubTrigger
export const MenubarTrigger: typeof import("../components/ui/menubar/index").MenubarTrigger
export const NavigationMenu: typeof import("../components/ui/navigation-menu/index").NavigationMenu
export const NavigationMenuContent: typeof import("../components/ui/navigation-menu/index").NavigationMenuContent
export const NavigationMenuIndicator: typeof import("../components/ui/navigation-menu/index").NavigationMenuIndicator
export const NavigationMenuItem: typeof import("../components/ui/navigation-menu/index").NavigationMenuItem
export const NavigationMenuLink: typeof import("../components/ui/navigation-menu/index").NavigationMenuLink
export const NavigationMenuList: typeof import("../components/ui/navigation-menu/index").NavigationMenuList
export const NavigationMenuTrigger: typeof import("../components/ui/navigation-menu/index").NavigationMenuTrigger
export const NavigationMenuViewport: typeof import("../components/ui/navigation-menu/index").NavigationMenuViewport
export const Pagination: typeof import("../components/ui/pagination/index").Pagination
export const PaginationContent: typeof import("../components/ui/pagination/index").PaginationContent
export const PaginationEllipsis: typeof import("../components/ui/pagination/index").PaginationEllipsis
export const PaginationFirst: typeof import("../components/ui/pagination/index").PaginationFirst
export const PaginationItem: typeof import("../components/ui/pagination/index").PaginationItem
export const PaginationLast: typeof import("../components/ui/pagination/index").PaginationLast
export const PaginationNext: typeof import("../components/ui/pagination/index").PaginationNext
export const PaginationPrevious: typeof import("../components/ui/pagination/index").PaginationPrevious
export const Popover: typeof import("../components/ui/popover/index").Popover
export const PopoverAnchor: typeof import("../components/ui/popover/index").PopoverAnchor
export const PopoverContent: typeof import("../components/ui/popover/index").PopoverContent
export const PopoverTrigger: typeof import("../components/ui/popover/index").PopoverTrigger
export const Select: typeof import("../components/ui/select/index").Select
export const SelectContent: typeof import("../components/ui/select/index").SelectContent
export const SelectGroup: typeof import("../components/ui/select/index").SelectGroup
export const SelectItem: typeof import("../components/ui/select/index").SelectItem
export const SelectItemText: typeof import("../components/ui/select/index").SelectItemText
export const SelectLabel: typeof import("../components/ui/select/index").SelectLabel
export const SelectScrollDownButton: typeof import("../components/ui/select/index").SelectScrollDownButton
export const SelectScrollUpButton: typeof import("../components/ui/select/index").SelectScrollUpButton
export const SelectSeparator: typeof import("../components/ui/select/index").SelectSeparator
export const SelectTrigger: typeof import("../components/ui/select/index").SelectTrigger
export const SelectValue: typeof import("../components/ui/select/index").SelectValue
export const Separator: typeof import("../components/ui/separator/index").Separator
export const Sheet: typeof import("../components/ui/sheet/index").Sheet
export const SheetClose: typeof import("../components/ui/sheet/index").SheetClose
export const SheetContent: typeof import("../components/ui/sheet/index").SheetContent
export const SheetDescription: typeof import("../components/ui/sheet/index").SheetDescription
export const SheetFooter: typeof import("../components/ui/sheet/index").SheetFooter
export const SheetHeader: typeof import("../components/ui/sheet/index").SheetHeader
export const SheetOverlay: typeof import("../components/ui/sheet/SheetOverlay.vue").default
export const SheetTitle: typeof import("../components/ui/sheet/index").SheetTitle
export const SheetTrigger: typeof import("../components/ui/sheet/index").SheetTrigger
export const Sidebar: typeof import("../components/ui/sidebar/index").Sidebar
export const SidebarContent: typeof import("../components/ui/sidebar/index").SidebarContent
export const SidebarFooter: typeof import("../components/ui/sidebar/index").SidebarFooter
export const SidebarGroup: typeof import("../components/ui/sidebar/index").SidebarGroup
export const SidebarGroupAction: typeof import("../components/ui/sidebar/index").SidebarGroupAction
export const SidebarGroupContent: typeof import("../components/ui/sidebar/index").SidebarGroupContent
export const SidebarGroupLabel: typeof import("../components/ui/sidebar/index").SidebarGroupLabel
export const SidebarHeader: typeof import("../components/ui/sidebar/index").SidebarHeader
export const SidebarInput: typeof import("../components/ui/sidebar/index").SidebarInput
export const SidebarInset: typeof import("../components/ui/sidebar/index").SidebarInset
export const SidebarMenu: typeof import("../components/ui/sidebar/index").SidebarMenu
export const SidebarMenuAction: typeof import("../components/ui/sidebar/index").SidebarMenuAction
export const SidebarMenuBadge: typeof import("../components/ui/sidebar/index").SidebarMenuBadge
export const SidebarMenuButton: typeof import("../components/ui/sidebar/index").SidebarMenuButton
export const SidebarMenuButtonChild: typeof import("../components/ui/sidebar/SidebarMenuButtonChild.vue").default
export const SidebarMenuItem: typeof import("../components/ui/sidebar/index").SidebarMenuItem
export const SidebarMenuSkeleton: typeof import("../components/ui/sidebar/index").SidebarMenuSkeleton
export const SidebarMenuSub: typeof import("../components/ui/sidebar/index").SidebarMenuSub
export const SidebarMenuSubButton: typeof import("../components/ui/sidebar/index").SidebarMenuSubButton
export const SidebarMenuSubItem: typeof import("../components/ui/sidebar/index").SidebarMenuSubItem
export const SidebarProvider: typeof import("../components/ui/sidebar/index").SidebarProvider
export const SidebarRail: typeof import("../components/ui/sidebar/index").SidebarRail
export const SidebarSeparator: typeof import("../components/ui/sidebar/index").SidebarSeparator
export const SidebarTrigger: typeof import("../components/ui/sidebar/index").SidebarTrigger
export const SidebarUtils: typeof import("../components/ui/sidebar/utils").default
export const Skeleton: typeof import("../components/ui/skeleton/index").Skeleton
export const Sonner: typeof import("../components/ui/sonner/Sonner.vue").default
export const Stepper: typeof import("../components/ui/stepper/index").Stepper
export const StepperDescription: typeof import("../components/ui/stepper/index").StepperDescription
export const StepperIndicator: typeof import("../components/ui/stepper/index").StepperIndicator
export const StepperItem: typeof import("../components/ui/stepper/index").StepperItem
export const StepperSeparator: typeof import("../components/ui/stepper/index").StepperSeparator
export const StepperTitle: typeof import("../components/ui/stepper/index").StepperTitle
export const StepperTrigger: typeof import("../components/ui/stepper/index").StepperTrigger
export const Table: typeof import("../components/ui/table/index").Table
export const TableBody: typeof import("../components/ui/table/index").TableBody
export const TableCaption: typeof import("../components/ui/table/index").TableCaption
export const TableCell: typeof import("../components/ui/table/index").TableCell
export const TableEmpty: typeof import("../components/ui/table/index").TableEmpty
export const TableFooter: typeof import("../components/ui/table/index").TableFooter
export const TableHead: typeof import("../components/ui/table/index").TableHead
export const TableHeader: typeof import("../components/ui/table/index").TableHeader
export const TableRow: typeof import("../components/ui/table/index").TableRow
export const TableUtils: typeof import("../components/ui/table/utils").default
export const Tabs: typeof import("../components/ui/tabs/index").Tabs
export const TabsContent: typeof import("../components/ui/tabs/index").TabsContent
export const TabsList: typeof import("../components/ui/tabs/index").TabsList
export const TabsTrigger: typeof import("../components/ui/tabs/index").TabsTrigger
export const Textarea: typeof import("../components/ui/textarea/index").Textarea
export const Tooltip: typeof import("../components/ui/tooltip/index").Tooltip
export const TooltipContent: typeof import("../components/ui/tooltip/index").TooltipContent
export const TooltipProvider: typeof import("../components/ui/tooltip/index").TooltipProvider
export const TooltipTrigger: typeof import("../components/ui/tooltip/index").TooltipTrigger
export const AuthUser: typeof import("../components/AuthUser.vue").default
export const Countdown: typeof import("../components/Countdown.vue").default
export const DatePicker: typeof import("../components/DatePicker.vue").default
export const TiptapEditor: typeof import("../components/TiptapEditor.vue").default
export const UserInfo: typeof import("../components/UserInfo.vue").default
export const Brand: typeof import("../components/brand.vue").default
export const Chart: typeof import("../components/chart.vue").default
export const Icon: typeof import("../components/icon.vue").default
export const Map: typeof import("../components/map.client.vue").default
export const PagesDashboardEventCategoryForm: typeof import("../components/pages/dashboard/event/category/Form.vue").default
export const PagesDashboardEventCategoryItem: typeof import("../components/pages/dashboard/event/category/Item.vue").default
export const PagesDashboardEventCategoryList: typeof import("../components/pages/dashboard/event/category/List.vue").default
export const PagesDashboardEventCheckpointForm: typeof import("../components/pages/dashboard/event/checkpoint/form.vue").default
export const PagesDashboardEventCheckpointList: typeof import("../components/pages/dashboard/event/checkpoint/list.vue").default
export const PagesDashboardEventDescription: typeof import("../components/pages/dashboard/event/description.vue").default
export const PagesDashboardEventGalleryForm: typeof import("../components/pages/dashboard/event/gallery/form.vue").default
export const PagesDashboardEventGalleryList: typeof import("../components/pages/dashboard/event/gallery/list.vue").default
export const PagesDashboardEventImageUpload: typeof import("../components/pages/dashboard/event/imageUpload.vue").default
export const PagesDashboardEventMapUpload: typeof import("../components/pages/dashboard/event/mapUpload.vue").default
export const PagesDashboardEventPaymentForm: typeof import("../components/pages/dashboard/event/payment/form.vue").default
export const PagesDashboardEventPaymentList: typeof import("../components/pages/dashboard/event/payment/list.vue").default
export const PagesDashboardEventRunnerItem: typeof import("../components/pages/dashboard/event/runner/RunnerItem.vue").default
export const PagesDashboardEventRunnerList: typeof import("../components/pages/dashboard/event/runner/list.vue").default
export const PagesDashboardEventSettingsList: typeof import("../components/pages/dashboard/event/settings/list.vue").default
export const PagesDashboardEventSponsorForm: typeof import("../components/pages/dashboard/event/sponsor/form.vue").default
export const PagesDashboardEventSponsorList: typeof import("../components/pages/dashboard/event/sponsor/list.vue").default
export const PagesDashboardEventStagesForm: typeof import("../components/pages/dashboard/event/stages/form.vue").default
export const PagesDashboardEventStagesList: typeof import("../components/pages/dashboard/event/stages/list.vue").default
export const PagesDashboardEventVolunteerAssignCheckpointForm: typeof import("../components/pages/dashboard/event/volunteer/AssignCheckpointForm.vue").default
export const PagesDashboardEventVolunteerList: typeof import("../components/pages/dashboard/event/volunteer/list.vue").default
export const PagesDashboardSponsorTypeForm: typeof import("../components/pages/dashboard/sponsor_type/Form.vue").default
export const PagesDashboardVolunteerEventList: typeof import("../components/pages/dashboard/volunteer/EventList.vue").default
export const PagesDashboardVolunteerRunner: typeof import("../components/pages/dashboard/volunteer/Runner.vue").default
export const PagesDefaultHomeBanner: typeof import("../components/pages/default/home/banner.vue").default
export const PagesDefaultHomeCard: typeof import("../components/pages/default/home/card.vue").default
export const PagesDefaultNewsletter: typeof import("../components/pages/default/newsletter.vue").default
export const PagesDefaultRacesRegistrationForm: typeof import("../components/pages/default/races/registrationForm.vue").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index").DropdownMenuPortal
export const ComboboxCancel: typeof import("../components/ui/combobox/index").ComboboxCancel
export const Toaster: typeof import("../components/ui/sonner/index").Toaster
export const AreaChart: typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaChart
export const AreaStackedChart: typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaStackedChart
export const LineChart: typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").LineChart
export const BarChart: typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").BarChart
export const DonutChart: typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").DonutChart
export const TiptapEditorContent: typeof import("@tiptap/vue-3").EditorContent
export const TiptapFloatingMenu: typeof import("@tiptap/vue-3").FloatingMenu
export const TiptapBubbleMenu: typeof import("@tiptap/vue-3").BubbleMenu
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyAccordion: LazyComponent<typeof import("../components/ui/accordion/index").Accordion>
export const LazyAccordionContent: LazyComponent<typeof import("../components/ui/accordion/index").AccordionContent>
export const LazyAccordionItem: LazyComponent<typeof import("../components/ui/accordion/index").AccordionItem>
export const LazyAccordionTrigger: LazyComponent<typeof import("../components/ui/accordion/index").AccordionTrigger>
export const LazyAlert: LazyComponent<typeof import("../components/ui/alert/index").Alert>
export const LazyAlertDescription: LazyComponent<typeof import("../components/ui/alert/index").AlertDescription>
export const LazyAlertTitle: LazyComponent<typeof import("../components/ui/alert/index").AlertTitle>
export const LazyAvatar: LazyComponent<typeof import("../components/ui/avatar/index").Avatar>
export const LazyAvatarFallback: LazyComponent<typeof import("../components/ui/avatar/index").AvatarFallback>
export const LazyAvatarImage: LazyComponent<typeof import("../components/ui/avatar/index").AvatarImage>
export const LazyBadge: LazyComponent<typeof import("../components/ui/badge/index").Badge>
export const LazyButton: LazyComponent<typeof import("../components/ui/button/index").Button>
export const LazyCalendar: LazyComponent<typeof import("../components/ui/calendar/index").Calendar>
export const LazyCalendarCell: LazyComponent<typeof import("../components/ui/calendar/index").CalendarCell>
export const LazyCalendarCellTrigger: LazyComponent<typeof import("../components/ui/calendar/index").CalendarCellTrigger>
export const LazyCalendarGrid: LazyComponent<typeof import("../components/ui/calendar/index").CalendarGrid>
export const LazyCalendarGridBody: LazyComponent<typeof import("../components/ui/calendar/index").CalendarGridBody>
export const LazyCalendarGridHead: LazyComponent<typeof import("../components/ui/calendar/index").CalendarGridHead>
export const LazyCalendarGridRow: LazyComponent<typeof import("../components/ui/calendar/index").CalendarGridRow>
export const LazyCalendarHeadCell: LazyComponent<typeof import("../components/ui/calendar/index").CalendarHeadCell>
export const LazyCalendarHeader: LazyComponent<typeof import("../components/ui/calendar/index").CalendarHeader>
export const LazyCalendarHeading: LazyComponent<typeof import("../components/ui/calendar/index").CalendarHeading>
export const LazyCalendarNextButton: LazyComponent<typeof import("../components/ui/calendar/index").CalendarNextButton>
export const LazyCalendarPrevButton: LazyComponent<typeof import("../components/ui/calendar/index").CalendarPrevButton>
export const LazyCheckbox: LazyComponent<typeof import("../components/ui/checkbox/index").Checkbox>
export const LazyCombobox: LazyComponent<typeof import("../components/ui/combobox/index").Combobox>
export const LazyComboboxAnchor: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxAnchor>
export const LazyComboboxEmpty: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxEmpty>
export const LazyComboboxGroup: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxGroup>
export const LazyComboboxInput: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxInput>
export const LazyComboboxItem: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxItem>
export const LazyComboboxItemIndicator: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxItemIndicator>
export const LazyComboboxList: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxList>
export const LazyComboboxSeparator: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxSeparator>
export const LazyComboboxTrigger: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxTrigger>
export const LazyComboboxViewport: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxViewport>
export const LazyDialog: LazyComponent<typeof import("../components/ui/dialog/index").Dialog>
export const LazyDialogClose: LazyComponent<typeof import("../components/ui/dialog/index").DialogClose>
export const LazyDialogContent: LazyComponent<typeof import("../components/ui/dialog/index").DialogContent>
export const LazyDialogDescription: LazyComponent<typeof import("../components/ui/dialog/index").DialogDescription>
export const LazyDialogFooter: LazyComponent<typeof import("../components/ui/dialog/index").DialogFooter>
export const LazyDialogHeader: LazyComponent<typeof import("../components/ui/dialog/index").DialogHeader>
export const LazyDialogOverlay: LazyComponent<typeof import("../components/ui/dialog/index").DialogOverlay>
export const LazyDialogScrollContent: LazyComponent<typeof import("../components/ui/dialog/index").DialogScrollContent>
export const LazyDialogTitle: LazyComponent<typeof import("../components/ui/dialog/index").DialogTitle>
export const LazyDialogTrigger: LazyComponent<typeof import("../components/ui/dialog/index").DialogTrigger>
export const LazyDropdownMenu: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenu>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuCheckboxItem>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuContent>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuGroup>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuItem>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuLabel>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuRadioGroup>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuRadioItem>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuSeparator>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuShortcut>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuSub>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuSubContent>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuSubTrigger>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuTrigger>
export const LazyInputGroup: LazyComponent<typeof import("../components/ui/input-group/index").InputGroup>
export const LazyInputGroupAddon: LazyComponent<typeof import("../components/ui/input-group/index").InputGroupAddon>
export const LazyInputGroupButton: LazyComponent<typeof import("../components/ui/input-group/index").InputGroupButton>
export const LazyInputGroupInput: LazyComponent<typeof import("../components/ui/input-group/index").InputGroupInput>
export const LazyInputGroupText: LazyComponent<typeof import("../components/ui/input-group/index").InputGroupText>
export const LazyInputGroupTextarea: LazyComponent<typeof import("../components/ui/input-group/index").InputGroupTextarea>
export const LazyInput: LazyComponent<typeof import("../components/ui/input/index").Input>
export const LazyLabel: LazyComponent<typeof import("../components/ui/label/index").Label>
export const LazyMenubar: LazyComponent<typeof import("../components/ui/menubar/index").Menubar>
export const LazyMenubarCheckboxItem: LazyComponent<typeof import("../components/ui/menubar/index").MenubarCheckboxItem>
export const LazyMenubarContent: LazyComponent<typeof import("../components/ui/menubar/index").MenubarContent>
export const LazyMenubarGroup: LazyComponent<typeof import("../components/ui/menubar/index").MenubarGroup>
export const LazyMenubarItem: LazyComponent<typeof import("../components/ui/menubar/index").MenubarItem>
export const LazyMenubarLabel: LazyComponent<typeof import("../components/ui/menubar/index").MenubarLabel>
export const LazyMenubarMenu: LazyComponent<typeof import("../components/ui/menubar/index").MenubarMenu>
export const LazyMenubarRadioGroup: LazyComponent<typeof import("../components/ui/menubar/index").MenubarRadioGroup>
export const LazyMenubarRadioItem: LazyComponent<typeof import("../components/ui/menubar/index").MenubarRadioItem>
export const LazyMenubarSeparator: LazyComponent<typeof import("../components/ui/menubar/index").MenubarSeparator>
export const LazyMenubarShortcut: LazyComponent<typeof import("../components/ui/menubar/index").MenubarShortcut>
export const LazyMenubarSub: LazyComponent<typeof import("../components/ui/menubar/index").MenubarSub>
export const LazyMenubarSubContent: LazyComponent<typeof import("../components/ui/menubar/index").MenubarSubContent>
export const LazyMenubarSubTrigger: LazyComponent<typeof import("../components/ui/menubar/index").MenubarSubTrigger>
export const LazyMenubarTrigger: LazyComponent<typeof import("../components/ui/menubar/index").MenubarTrigger>
export const LazyNavigationMenu: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenu>
export const LazyNavigationMenuContent: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuContent>
export const LazyNavigationMenuIndicator: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuIndicator>
export const LazyNavigationMenuItem: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuItem>
export const LazyNavigationMenuLink: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuLink>
export const LazyNavigationMenuList: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuList>
export const LazyNavigationMenuTrigger: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuTrigger>
export const LazyNavigationMenuViewport: LazyComponent<typeof import("../components/ui/navigation-menu/index").NavigationMenuViewport>
export const LazyPagination: LazyComponent<typeof import("../components/ui/pagination/index").Pagination>
export const LazyPaginationContent: LazyComponent<typeof import("../components/ui/pagination/index").PaginationContent>
export const LazyPaginationEllipsis: LazyComponent<typeof import("../components/ui/pagination/index").PaginationEllipsis>
export const LazyPaginationFirst: LazyComponent<typeof import("../components/ui/pagination/index").PaginationFirst>
export const LazyPaginationItem: LazyComponent<typeof import("../components/ui/pagination/index").PaginationItem>
export const LazyPaginationLast: LazyComponent<typeof import("../components/ui/pagination/index").PaginationLast>
export const LazyPaginationNext: LazyComponent<typeof import("../components/ui/pagination/index").PaginationNext>
export const LazyPaginationPrevious: LazyComponent<typeof import("../components/ui/pagination/index").PaginationPrevious>
export const LazyPopover: LazyComponent<typeof import("../components/ui/popover/index").Popover>
export const LazyPopoverAnchor: LazyComponent<typeof import("../components/ui/popover/index").PopoverAnchor>
export const LazyPopoverContent: LazyComponent<typeof import("../components/ui/popover/index").PopoverContent>
export const LazyPopoverTrigger: LazyComponent<typeof import("../components/ui/popover/index").PopoverTrigger>
export const LazySelect: LazyComponent<typeof import("../components/ui/select/index").Select>
export const LazySelectContent: LazyComponent<typeof import("../components/ui/select/index").SelectContent>
export const LazySelectGroup: LazyComponent<typeof import("../components/ui/select/index").SelectGroup>
export const LazySelectItem: LazyComponent<typeof import("../components/ui/select/index").SelectItem>
export const LazySelectItemText: LazyComponent<typeof import("../components/ui/select/index").SelectItemText>
export const LazySelectLabel: LazyComponent<typeof import("../components/ui/select/index").SelectLabel>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../components/ui/select/index").SelectScrollDownButton>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../components/ui/select/index").SelectScrollUpButton>
export const LazySelectSeparator: LazyComponent<typeof import("../components/ui/select/index").SelectSeparator>
export const LazySelectTrigger: LazyComponent<typeof import("../components/ui/select/index").SelectTrigger>
export const LazySelectValue: LazyComponent<typeof import("../components/ui/select/index").SelectValue>
export const LazySeparator: LazyComponent<typeof import("../components/ui/separator/index").Separator>
export const LazySheet: LazyComponent<typeof import("../components/ui/sheet/index").Sheet>
export const LazySheetClose: LazyComponent<typeof import("../components/ui/sheet/index").SheetClose>
export const LazySheetContent: LazyComponent<typeof import("../components/ui/sheet/index").SheetContent>
export const LazySheetDescription: LazyComponent<typeof import("../components/ui/sheet/index").SheetDescription>
export const LazySheetFooter: LazyComponent<typeof import("../components/ui/sheet/index").SheetFooter>
export const LazySheetHeader: LazyComponent<typeof import("../components/ui/sheet/index").SheetHeader>
export const LazySheetOverlay: LazyComponent<typeof import("../components/ui/sheet/SheetOverlay.vue").default>
export const LazySheetTitle: LazyComponent<typeof import("../components/ui/sheet/index").SheetTitle>
export const LazySheetTrigger: LazyComponent<typeof import("../components/ui/sheet/index").SheetTrigger>
export const LazySidebar: LazyComponent<typeof import("../components/ui/sidebar/index").Sidebar>
export const LazySidebarContent: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarContent>
export const LazySidebarFooter: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarFooter>
export const LazySidebarGroup: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarGroup>
export const LazySidebarGroupAction: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarGroupAction>
export const LazySidebarGroupContent: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarGroupContent>
export const LazySidebarGroupLabel: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarGroupLabel>
export const LazySidebarHeader: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarHeader>
export const LazySidebarInput: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarInput>
export const LazySidebarInset: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarInset>
export const LazySidebarMenu: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenu>
export const LazySidebarMenuAction: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuAction>
export const LazySidebarMenuBadge: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuBadge>
export const LazySidebarMenuButton: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuButton>
export const LazySidebarMenuButtonChild: LazyComponent<typeof import("../components/ui/sidebar/SidebarMenuButtonChild.vue").default>
export const LazySidebarMenuItem: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuItem>
export const LazySidebarMenuSkeleton: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuSkeleton>
export const LazySidebarMenuSub: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuSub>
export const LazySidebarMenuSubButton: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuSubButton>
export const LazySidebarMenuSubItem: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarMenuSubItem>
export const LazySidebarProvider: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarProvider>
export const LazySidebarRail: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarRail>
export const LazySidebarSeparator: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarSeparator>
export const LazySidebarTrigger: LazyComponent<typeof import("../components/ui/sidebar/index").SidebarTrigger>
export const LazySidebarUtils: LazyComponent<typeof import("../components/ui/sidebar/utils").default>
export const LazySkeleton: LazyComponent<typeof import("../components/ui/skeleton/index").Skeleton>
export const LazySonner: LazyComponent<typeof import("../components/ui/sonner/Sonner.vue").default>
export const LazyStepper: LazyComponent<typeof import("../components/ui/stepper/index").Stepper>
export const LazyStepperDescription: LazyComponent<typeof import("../components/ui/stepper/index").StepperDescription>
export const LazyStepperIndicator: LazyComponent<typeof import("../components/ui/stepper/index").StepperIndicator>
export const LazyStepperItem: LazyComponent<typeof import("../components/ui/stepper/index").StepperItem>
export const LazyStepperSeparator: LazyComponent<typeof import("../components/ui/stepper/index").StepperSeparator>
export const LazyStepperTitle: LazyComponent<typeof import("../components/ui/stepper/index").StepperTitle>
export const LazyStepperTrigger: LazyComponent<typeof import("../components/ui/stepper/index").StepperTrigger>
export const LazyTable: LazyComponent<typeof import("../components/ui/table/index").Table>
export const LazyTableBody: LazyComponent<typeof import("../components/ui/table/index").TableBody>
export const LazyTableCaption: LazyComponent<typeof import("../components/ui/table/index").TableCaption>
export const LazyTableCell: LazyComponent<typeof import("../components/ui/table/index").TableCell>
export const LazyTableEmpty: LazyComponent<typeof import("../components/ui/table/index").TableEmpty>
export const LazyTableFooter: LazyComponent<typeof import("../components/ui/table/index").TableFooter>
export const LazyTableHead: LazyComponent<typeof import("../components/ui/table/index").TableHead>
export const LazyTableHeader: LazyComponent<typeof import("../components/ui/table/index").TableHeader>
export const LazyTableRow: LazyComponent<typeof import("../components/ui/table/index").TableRow>
export const LazyTableUtils: LazyComponent<typeof import("../components/ui/table/utils").default>
export const LazyTabs: LazyComponent<typeof import("../components/ui/tabs/index").Tabs>
export const LazyTabsContent: LazyComponent<typeof import("../components/ui/tabs/index").TabsContent>
export const LazyTabsList: LazyComponent<typeof import("../components/ui/tabs/index").TabsList>
export const LazyTabsTrigger: LazyComponent<typeof import("../components/ui/tabs/index").TabsTrigger>
export const LazyTextarea: LazyComponent<typeof import("../components/ui/textarea/index").Textarea>
export const LazyTooltip: LazyComponent<typeof import("../components/ui/tooltip/index").Tooltip>
export const LazyTooltipContent: LazyComponent<typeof import("../components/ui/tooltip/index").TooltipContent>
export const LazyTooltipProvider: LazyComponent<typeof import("../components/ui/tooltip/index").TooltipProvider>
export const LazyTooltipTrigger: LazyComponent<typeof import("../components/ui/tooltip/index").TooltipTrigger>
export const LazyAuthUser: LazyComponent<typeof import("../components/AuthUser.vue").default>
export const LazyCountdown: LazyComponent<typeof import("../components/Countdown.vue").default>
export const LazyDatePicker: LazyComponent<typeof import("../components/DatePicker.vue").default>
export const LazyTiptapEditor: LazyComponent<typeof import("../components/TiptapEditor.vue").default>
export const LazyUserInfo: LazyComponent<typeof import("../components/UserInfo.vue").default>
export const LazyBrand: LazyComponent<typeof import("../components/brand.vue").default>
export const LazyChart: LazyComponent<typeof import("../components/chart.vue").default>
export const LazyIcon: LazyComponent<typeof import("../components/icon.vue").default>
export const LazyMap: LazyComponent<typeof import("../components/map.client.vue").default>
export const LazyPagesDashboardEventCategoryForm: LazyComponent<typeof import("../components/pages/dashboard/event/category/Form.vue").default>
export const LazyPagesDashboardEventCategoryItem: LazyComponent<typeof import("../components/pages/dashboard/event/category/Item.vue").default>
export const LazyPagesDashboardEventCategoryList: LazyComponent<typeof import("../components/pages/dashboard/event/category/List.vue").default>
export const LazyPagesDashboardEventCheckpointForm: LazyComponent<typeof import("../components/pages/dashboard/event/checkpoint/form.vue").default>
export const LazyPagesDashboardEventCheckpointList: LazyComponent<typeof import("../components/pages/dashboard/event/checkpoint/list.vue").default>
export const LazyPagesDashboardEventDescription: LazyComponent<typeof import("../components/pages/dashboard/event/description.vue").default>
export const LazyPagesDashboardEventGalleryForm: LazyComponent<typeof import("../components/pages/dashboard/event/gallery/form.vue").default>
export const LazyPagesDashboardEventGalleryList: LazyComponent<typeof import("../components/pages/dashboard/event/gallery/list.vue").default>
export const LazyPagesDashboardEventImageUpload: LazyComponent<typeof import("../components/pages/dashboard/event/imageUpload.vue").default>
export const LazyPagesDashboardEventMapUpload: LazyComponent<typeof import("../components/pages/dashboard/event/mapUpload.vue").default>
export const LazyPagesDashboardEventPaymentForm: LazyComponent<typeof import("../components/pages/dashboard/event/payment/form.vue").default>
export const LazyPagesDashboardEventPaymentList: LazyComponent<typeof import("../components/pages/dashboard/event/payment/list.vue").default>
export const LazyPagesDashboardEventRunnerItem: LazyComponent<typeof import("../components/pages/dashboard/event/runner/RunnerItem.vue").default>
export const LazyPagesDashboardEventRunnerList: LazyComponent<typeof import("../components/pages/dashboard/event/runner/list.vue").default>
export const LazyPagesDashboardEventSettingsList: LazyComponent<typeof import("../components/pages/dashboard/event/settings/list.vue").default>
export const LazyPagesDashboardEventSponsorForm: LazyComponent<typeof import("../components/pages/dashboard/event/sponsor/form.vue").default>
export const LazyPagesDashboardEventSponsorList: LazyComponent<typeof import("../components/pages/dashboard/event/sponsor/list.vue").default>
export const LazyPagesDashboardEventStagesForm: LazyComponent<typeof import("../components/pages/dashboard/event/stages/form.vue").default>
export const LazyPagesDashboardEventStagesList: LazyComponent<typeof import("../components/pages/dashboard/event/stages/list.vue").default>
export const LazyPagesDashboardEventVolunteerAssignCheckpointForm: LazyComponent<typeof import("../components/pages/dashboard/event/volunteer/AssignCheckpointForm.vue").default>
export const LazyPagesDashboardEventVolunteerList: LazyComponent<typeof import("../components/pages/dashboard/event/volunteer/list.vue").default>
export const LazyPagesDashboardSponsorTypeForm: LazyComponent<typeof import("../components/pages/dashboard/sponsor_type/Form.vue").default>
export const LazyPagesDashboardVolunteerEventList: LazyComponent<typeof import("../components/pages/dashboard/volunteer/EventList.vue").default>
export const LazyPagesDashboardVolunteerRunner: LazyComponent<typeof import("../components/pages/dashboard/volunteer/Runner.vue").default>
export const LazyPagesDefaultHomeBanner: LazyComponent<typeof import("../components/pages/default/home/banner.vue").default>
export const LazyPagesDefaultHomeCard: LazyComponent<typeof import("../components/pages/default/home/card.vue").default>
export const LazyPagesDefaultNewsletter: LazyComponent<typeof import("../components/pages/default/newsletter.vue").default>
export const LazyPagesDefaultRacesRegistrationForm: LazyComponent<typeof import("../components/pages/default/races/registrationForm.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../components/ui/dropdown-menu/index").DropdownMenuPortal>
export const LazyComboboxCancel: LazyComponent<typeof import("../components/ui/combobox/index").ComboboxCancel>
export const LazyToaster: LazyComponent<typeof import("../components/ui/sonner/index").Toaster>
export const LazyAreaChart: LazyComponent<typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaChart>
export const LazyAreaStackedChart: LazyComponent<typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaStackedChart>
export const LazyLineChart: LazyComponent<typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").LineChart>
export const LazyBarChart: LazyComponent<typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").BarChart>
export const LazyDonutChart: LazyComponent<typeof import("../node_modules/nuxt-charts/dist/runtime/vue-chrts").DonutChart>
export const LazyTiptapEditorContent: LazyComponent<typeof import("@tiptap/vue-3").EditorContent>
export const LazyTiptapFloatingMenu: LazyComponent<typeof import("@tiptap/vue-3").FloatingMenu>
export const LazyTiptapBubbleMenu: LazyComponent<typeof import("@tiptap/vue-3").BubbleMenu>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
