
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'Accordion': typeof import("../../components/ui/accordion/index").Accordion
  'AccordionContent': typeof import("../../components/ui/accordion/index").AccordionContent
  'AccordionItem': typeof import("../../components/ui/accordion/index").AccordionItem
  'AccordionTrigger': typeof import("../../components/ui/accordion/index").AccordionTrigger
  'Alert': typeof import("../../components/ui/alert/index").Alert
  'AlertDescription': typeof import("../../components/ui/alert/index").AlertDescription
  'AlertTitle': typeof import("../../components/ui/alert/index").AlertTitle
  'Avatar': typeof import("../../components/ui/avatar/index").Avatar
  'AvatarFallback': typeof import("../../components/ui/avatar/index").AvatarFallback
  'AvatarImage': typeof import("../../components/ui/avatar/index").AvatarImage
  'Badge': typeof import("../../components/ui/badge/index").Badge
  'Button': typeof import("../../components/ui/button/index").Button
  'Calendar': typeof import("../../components/ui/calendar/index").Calendar
  'CalendarCell': typeof import("../../components/ui/calendar/index").CalendarCell
  'CalendarCellTrigger': typeof import("../../components/ui/calendar/index").CalendarCellTrigger
  'CalendarGrid': typeof import("../../components/ui/calendar/index").CalendarGrid
  'CalendarGridBody': typeof import("../../components/ui/calendar/index").CalendarGridBody
  'CalendarGridHead': typeof import("../../components/ui/calendar/index").CalendarGridHead
  'CalendarGridRow': typeof import("../../components/ui/calendar/index").CalendarGridRow
  'CalendarHeadCell': typeof import("../../components/ui/calendar/index").CalendarHeadCell
  'CalendarHeader': typeof import("../../components/ui/calendar/index").CalendarHeader
  'CalendarHeading': typeof import("../../components/ui/calendar/index").CalendarHeading
  'CalendarNextButton': typeof import("../../components/ui/calendar/index").CalendarNextButton
  'CalendarPrevButton': typeof import("../../components/ui/calendar/index").CalendarPrevButton
  'Checkbox': typeof import("../../components/ui/checkbox/index").Checkbox
  'Combobox': typeof import("../../components/ui/combobox/index").Combobox
  'ComboboxAnchor': typeof import("../../components/ui/combobox/index").ComboboxAnchor
  'ComboboxEmpty': typeof import("../../components/ui/combobox/index").ComboboxEmpty
  'ComboboxGroup': typeof import("../../components/ui/combobox/index").ComboboxGroup
  'ComboboxInput': typeof import("../../components/ui/combobox/index").ComboboxInput
  'ComboboxItem': typeof import("../../components/ui/combobox/index").ComboboxItem
  'ComboboxItemIndicator': typeof import("../../components/ui/combobox/index").ComboboxItemIndicator
  'ComboboxList': typeof import("../../components/ui/combobox/index").ComboboxList
  'ComboboxSeparator': typeof import("../../components/ui/combobox/index").ComboboxSeparator
  'ComboboxTrigger': typeof import("../../components/ui/combobox/index").ComboboxTrigger
  'ComboboxViewport': typeof import("../../components/ui/combobox/index").ComboboxViewport
  'Dialog': typeof import("../../components/ui/dialog/index").Dialog
  'DialogClose': typeof import("../../components/ui/dialog/index").DialogClose
  'DialogContent': typeof import("../../components/ui/dialog/index").DialogContent
  'DialogDescription': typeof import("../../components/ui/dialog/index").DialogDescription
  'DialogFooter': typeof import("../../components/ui/dialog/index").DialogFooter
  'DialogHeader': typeof import("../../components/ui/dialog/index").DialogHeader
  'DialogOverlay': typeof import("../../components/ui/dialog/index").DialogOverlay
  'DialogScrollContent': typeof import("../../components/ui/dialog/index").DialogScrollContent
  'DialogTitle': typeof import("../../components/ui/dialog/index").DialogTitle
  'DialogTrigger': typeof import("../../components/ui/dialog/index").DialogTrigger
  'DropdownMenu': typeof import("../../components/ui/dropdown-menu/index").DropdownMenu
  'DropdownMenuCheckboxItem': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuCheckboxItem
  'DropdownMenuContent': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuContent
  'DropdownMenuGroup': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuGroup
  'DropdownMenuItem': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuItem
  'DropdownMenuLabel': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuLabel
  'DropdownMenuRadioGroup': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuRadioGroup
  'DropdownMenuRadioItem': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuRadioItem
  'DropdownMenuSeparator': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSeparator
  'DropdownMenuShortcut': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuShortcut
  'DropdownMenuSub': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSub
  'DropdownMenuSubContent': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSubContent
  'DropdownMenuSubTrigger': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSubTrigger
  'DropdownMenuTrigger': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuTrigger
  'InputGroup': typeof import("../../components/ui/input-group/index").InputGroup
  'InputGroupAddon': typeof import("../../components/ui/input-group/index").InputGroupAddon
  'InputGroupButton': typeof import("../../components/ui/input-group/index").InputGroupButton
  'InputGroupInput': typeof import("../../components/ui/input-group/index").InputGroupInput
  'InputGroupText': typeof import("../../components/ui/input-group/index").InputGroupText
  'InputGroupTextarea': typeof import("../../components/ui/input-group/index").InputGroupTextarea
  'Input': typeof import("../../components/ui/input/index").Input
  'Label': typeof import("../../components/ui/label/index").Label
  'Menubar': typeof import("../../components/ui/menubar/index").Menubar
  'MenubarCheckboxItem': typeof import("../../components/ui/menubar/index").MenubarCheckboxItem
  'MenubarContent': typeof import("../../components/ui/menubar/index").MenubarContent
  'MenubarGroup': typeof import("../../components/ui/menubar/index").MenubarGroup
  'MenubarItem': typeof import("../../components/ui/menubar/index").MenubarItem
  'MenubarLabel': typeof import("../../components/ui/menubar/index").MenubarLabel
  'MenubarMenu': typeof import("../../components/ui/menubar/index").MenubarMenu
  'MenubarRadioGroup': typeof import("../../components/ui/menubar/index").MenubarRadioGroup
  'MenubarRadioItem': typeof import("../../components/ui/menubar/index").MenubarRadioItem
  'MenubarSeparator': typeof import("../../components/ui/menubar/index").MenubarSeparator
  'MenubarShortcut': typeof import("../../components/ui/menubar/index").MenubarShortcut
  'MenubarSub': typeof import("../../components/ui/menubar/index").MenubarSub
  'MenubarSubContent': typeof import("../../components/ui/menubar/index").MenubarSubContent
  'MenubarSubTrigger': typeof import("../../components/ui/menubar/index").MenubarSubTrigger
  'MenubarTrigger': typeof import("../../components/ui/menubar/index").MenubarTrigger
  'NavigationMenu': typeof import("../../components/ui/navigation-menu/index").NavigationMenu
  'NavigationMenuContent': typeof import("../../components/ui/navigation-menu/index").NavigationMenuContent
  'NavigationMenuIndicator': typeof import("../../components/ui/navigation-menu/index").NavigationMenuIndicator
  'NavigationMenuItem': typeof import("../../components/ui/navigation-menu/index").NavigationMenuItem
  'NavigationMenuLink': typeof import("../../components/ui/navigation-menu/index").NavigationMenuLink
  'NavigationMenuList': typeof import("../../components/ui/navigation-menu/index").NavigationMenuList
  'NavigationMenuTrigger': typeof import("../../components/ui/navigation-menu/index").NavigationMenuTrigger
  'NavigationMenuViewport': typeof import("../../components/ui/navigation-menu/index").NavigationMenuViewport
  'Pagination': typeof import("../../components/ui/pagination/index").Pagination
  'PaginationContent': typeof import("../../components/ui/pagination/index").PaginationContent
  'PaginationEllipsis': typeof import("../../components/ui/pagination/index").PaginationEllipsis
  'PaginationFirst': typeof import("../../components/ui/pagination/index").PaginationFirst
  'PaginationItem': typeof import("../../components/ui/pagination/index").PaginationItem
  'PaginationLast': typeof import("../../components/ui/pagination/index").PaginationLast
  'PaginationNext': typeof import("../../components/ui/pagination/index").PaginationNext
  'PaginationPrevious': typeof import("../../components/ui/pagination/index").PaginationPrevious
  'Popover': typeof import("../../components/ui/popover/index").Popover
  'PopoverAnchor': typeof import("../../components/ui/popover/index").PopoverAnchor
  'PopoverContent': typeof import("../../components/ui/popover/index").PopoverContent
  'PopoverTrigger': typeof import("../../components/ui/popover/index").PopoverTrigger
  'Select': typeof import("../../components/ui/select/index").Select
  'SelectContent': typeof import("../../components/ui/select/index").SelectContent
  'SelectGroup': typeof import("../../components/ui/select/index").SelectGroup
  'SelectItem': typeof import("../../components/ui/select/index").SelectItem
  'SelectItemText': typeof import("../../components/ui/select/index").SelectItemText
  'SelectLabel': typeof import("../../components/ui/select/index").SelectLabel
  'SelectScrollDownButton': typeof import("../../components/ui/select/index").SelectScrollDownButton
  'SelectScrollUpButton': typeof import("../../components/ui/select/index").SelectScrollUpButton
  'SelectSeparator': typeof import("../../components/ui/select/index").SelectSeparator
  'SelectTrigger': typeof import("../../components/ui/select/index").SelectTrigger
  'SelectValue': typeof import("../../components/ui/select/index").SelectValue
  'Separator': typeof import("../../components/ui/separator/index").Separator
  'Sheet': typeof import("../../components/ui/sheet/index").Sheet
  'SheetClose': typeof import("../../components/ui/sheet/index").SheetClose
  'SheetContent': typeof import("../../components/ui/sheet/index").SheetContent
  'SheetDescription': typeof import("../../components/ui/sheet/index").SheetDescription
  'SheetFooter': typeof import("../../components/ui/sheet/index").SheetFooter
  'SheetHeader': typeof import("../../components/ui/sheet/index").SheetHeader
  'SheetOverlay': typeof import("../../components/ui/sheet/SheetOverlay.vue").default
  'SheetTitle': typeof import("../../components/ui/sheet/index").SheetTitle
  'SheetTrigger': typeof import("../../components/ui/sheet/index").SheetTrigger
  'Sidebar': typeof import("../../components/ui/sidebar/index").Sidebar
  'SidebarContent': typeof import("../../components/ui/sidebar/index").SidebarContent
  'SidebarFooter': typeof import("../../components/ui/sidebar/index").SidebarFooter
  'SidebarGroup': typeof import("../../components/ui/sidebar/index").SidebarGroup
  'SidebarGroupAction': typeof import("../../components/ui/sidebar/index").SidebarGroupAction
  'SidebarGroupContent': typeof import("../../components/ui/sidebar/index").SidebarGroupContent
  'SidebarGroupLabel': typeof import("../../components/ui/sidebar/index").SidebarGroupLabel
  'SidebarHeader': typeof import("../../components/ui/sidebar/index").SidebarHeader
  'SidebarInput': typeof import("../../components/ui/sidebar/index").SidebarInput
  'SidebarInset': typeof import("../../components/ui/sidebar/index").SidebarInset
  'SidebarMenu': typeof import("../../components/ui/sidebar/index").SidebarMenu
  'SidebarMenuAction': typeof import("../../components/ui/sidebar/index").SidebarMenuAction
  'SidebarMenuBadge': typeof import("../../components/ui/sidebar/index").SidebarMenuBadge
  'SidebarMenuButton': typeof import("../../components/ui/sidebar/index").SidebarMenuButton
  'SidebarMenuButtonChild': typeof import("../../components/ui/sidebar/SidebarMenuButtonChild.vue").default
  'SidebarMenuItem': typeof import("../../components/ui/sidebar/index").SidebarMenuItem
  'SidebarMenuSkeleton': typeof import("../../components/ui/sidebar/index").SidebarMenuSkeleton
  'SidebarMenuSub': typeof import("../../components/ui/sidebar/index").SidebarMenuSub
  'SidebarMenuSubButton': typeof import("../../components/ui/sidebar/index").SidebarMenuSubButton
  'SidebarMenuSubItem': typeof import("../../components/ui/sidebar/index").SidebarMenuSubItem
  'SidebarProvider': typeof import("../../components/ui/sidebar/index").SidebarProvider
  'SidebarRail': typeof import("../../components/ui/sidebar/index").SidebarRail
  'SidebarSeparator': typeof import("../../components/ui/sidebar/index").SidebarSeparator
  'SidebarTrigger': typeof import("../../components/ui/sidebar/index").SidebarTrigger
  'SidebarUtils': typeof import("../../components/ui/sidebar/utils").default
  'Skeleton': typeof import("../../components/ui/skeleton/index").Skeleton
  'Sonner': typeof import("../../components/ui/sonner/Sonner.vue").default
  'Stepper': typeof import("../../components/ui/stepper/index").Stepper
  'StepperDescription': typeof import("../../components/ui/stepper/index").StepperDescription
  'StepperIndicator': typeof import("../../components/ui/stepper/index").StepperIndicator
  'StepperItem': typeof import("../../components/ui/stepper/index").StepperItem
  'StepperSeparator': typeof import("../../components/ui/stepper/index").StepperSeparator
  'StepperTitle': typeof import("../../components/ui/stepper/index").StepperTitle
  'StepperTrigger': typeof import("../../components/ui/stepper/index").StepperTrigger
  'Table': typeof import("../../components/ui/table/index").Table
  'TableBody': typeof import("../../components/ui/table/index").TableBody
  'TableCaption': typeof import("../../components/ui/table/index").TableCaption
  'TableCell': typeof import("../../components/ui/table/index").TableCell
  'TableEmpty': typeof import("../../components/ui/table/index").TableEmpty
  'TableFooter': typeof import("../../components/ui/table/index").TableFooter
  'TableHead': typeof import("../../components/ui/table/index").TableHead
  'TableHeader': typeof import("../../components/ui/table/index").TableHeader
  'TableRow': typeof import("../../components/ui/table/index").TableRow
  'TableUtils': typeof import("../../components/ui/table/utils").default
  'Tabs': typeof import("../../components/ui/tabs/index").Tabs
  'TabsContent': typeof import("../../components/ui/tabs/index").TabsContent
  'TabsList': typeof import("../../components/ui/tabs/index").TabsList
  'TabsTrigger': typeof import("../../components/ui/tabs/index").TabsTrigger
  'Textarea': typeof import("../../components/ui/textarea/index").Textarea
  'Tooltip': typeof import("../../components/ui/tooltip/index").Tooltip
  'TooltipContent': typeof import("../../components/ui/tooltip/index").TooltipContent
  'TooltipProvider': typeof import("../../components/ui/tooltip/index").TooltipProvider
  'TooltipTrigger': typeof import("../../components/ui/tooltip/index").TooltipTrigger
  'AuthUser': typeof import("../../components/AuthUser.vue").default
  'Countdown': typeof import("../../components/Countdown.vue").default
  'DatePicker': typeof import("../../components/DatePicker.vue").default
  'TiptapEditor': typeof import("../../components/TiptapEditor.vue").default
  'UserInfo': typeof import("../../components/UserInfo.vue").default
  'Brand': typeof import("../../components/brand.vue").default
  'Chart': typeof import("../../components/chart.vue").default
  'Icon': typeof import("../../components/icon.vue").default
  'Map': typeof import("../../components/map.client.vue").default
  'PagesDashboardEventCategoryForm': typeof import("../../components/pages/dashboard/event/category/Form.vue").default
  'PagesDashboardEventCategoryItem': typeof import("../../components/pages/dashboard/event/category/Item.vue").default
  'PagesDashboardEventCategoryList': typeof import("../../components/pages/dashboard/event/category/List.vue").default
  'PagesDashboardEventCheckpointForm': typeof import("../../components/pages/dashboard/event/checkpoint/form.vue").default
  'PagesDashboardEventCheckpointList': typeof import("../../components/pages/dashboard/event/checkpoint/list.vue").default
  'PagesDashboardEventDescription': typeof import("../../components/pages/dashboard/event/description.vue").default
  'PagesDashboardEventGalleryForm': typeof import("../../components/pages/dashboard/event/gallery/form.vue").default
  'PagesDashboardEventGalleryList': typeof import("../../components/pages/dashboard/event/gallery/list.vue").default
  'PagesDashboardEventImageUpload': typeof import("../../components/pages/dashboard/event/imageUpload.vue").default
  'PagesDashboardEventMapUpload': typeof import("../../components/pages/dashboard/event/mapUpload.vue").default
  'PagesDashboardEventPaymentForm': typeof import("../../components/pages/dashboard/event/payment/form.vue").default
  'PagesDashboardEventPaymentList': typeof import("../../components/pages/dashboard/event/payment/list.vue").default
  'PagesDashboardEventRunnerItem': typeof import("../../components/pages/dashboard/event/runner/RunnerItem.vue").default
  'PagesDashboardEventRunnerList': typeof import("../../components/pages/dashboard/event/runner/list.vue").default
  'PagesDashboardEventSettingsList': typeof import("../../components/pages/dashboard/event/settings/list.vue").default
  'PagesDashboardEventSponsorForm': typeof import("../../components/pages/dashboard/event/sponsor/form.vue").default
  'PagesDashboardEventSponsorList': typeof import("../../components/pages/dashboard/event/sponsor/list.vue").default
  'PagesDashboardEventStagesForm': typeof import("../../components/pages/dashboard/event/stages/form.vue").default
  'PagesDashboardEventStagesList': typeof import("../../components/pages/dashboard/event/stages/list.vue").default
  'PagesDashboardEventVolunteerAssignCheckpointForm': typeof import("../../components/pages/dashboard/event/volunteer/AssignCheckpointForm.vue").default
  'PagesDashboardEventVolunteerList': typeof import("../../components/pages/dashboard/event/volunteer/list.vue").default
  'PagesDashboardSponsorTypeForm': typeof import("../../components/pages/dashboard/sponsor_type/Form.vue").default
  'PagesDashboardVolunteerEventList': typeof import("../../components/pages/dashboard/volunteer/EventList.vue").default
  'PagesDashboardVolunteerRunner': typeof import("../../components/pages/dashboard/volunteer/Runner.vue").default
  'PagesDefaultHomeBanner': typeof import("../../components/pages/default/home/banner.vue").default
  'PagesDefaultHomeCard': typeof import("../../components/pages/default/home/card.vue").default
  'PagesDefaultNewsletter': typeof import("../../components/pages/default/newsletter.vue").default
  'PagesDefaultRacesRegistrationForm': typeof import("../../components/pages/default/races/registrationForm.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'ComboboxCancel': typeof import("../../components/ui/combobox/index").ComboboxCancel
  'DropdownMenuPortal': typeof import("../../components/ui/dropdown-menu/index").DropdownMenuPortal
  'Toaster': typeof import("../../components/ui/sonner/index").Toaster
  'AreaChart': typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaChart
  'AreaStackedChart': typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaStackedChart
  'LineChart': typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").LineChart
  'BarChart': typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").BarChart
  'DonutChart': typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").DonutChart
  'TiptapEditorContent': typeof import("@tiptap/vue-3").EditorContent
  'TiptapFloatingMenu': typeof import("@tiptap/vue-3").FloatingMenu
  'TiptapBubbleMenu': typeof import("@tiptap/vue-3").BubbleMenu
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyAccordion': LazyComponent<typeof import("../../components/ui/accordion/index").Accordion>
  'LazyAccordionContent': LazyComponent<typeof import("../../components/ui/accordion/index").AccordionContent>
  'LazyAccordionItem': LazyComponent<typeof import("../../components/ui/accordion/index").AccordionItem>
  'LazyAccordionTrigger': LazyComponent<typeof import("../../components/ui/accordion/index").AccordionTrigger>
  'LazyAlert': LazyComponent<typeof import("../../components/ui/alert/index").Alert>
  'LazyAlertDescription': LazyComponent<typeof import("../../components/ui/alert/index").AlertDescription>
  'LazyAlertTitle': LazyComponent<typeof import("../../components/ui/alert/index").AlertTitle>
  'LazyAvatar': LazyComponent<typeof import("../../components/ui/avatar/index").Avatar>
  'LazyAvatarFallback': LazyComponent<typeof import("../../components/ui/avatar/index").AvatarFallback>
  'LazyAvatarImage': LazyComponent<typeof import("../../components/ui/avatar/index").AvatarImage>
  'LazyBadge': LazyComponent<typeof import("../../components/ui/badge/index").Badge>
  'LazyButton': LazyComponent<typeof import("../../components/ui/button/index").Button>
  'LazyCalendar': LazyComponent<typeof import("../../components/ui/calendar/index").Calendar>
  'LazyCalendarCell': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarCell>
  'LazyCalendarCellTrigger': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarCellTrigger>
  'LazyCalendarGrid': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarGrid>
  'LazyCalendarGridBody': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarGridBody>
  'LazyCalendarGridHead': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarGridHead>
  'LazyCalendarGridRow': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarGridRow>
  'LazyCalendarHeadCell': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarHeadCell>
  'LazyCalendarHeader': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarHeader>
  'LazyCalendarHeading': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarHeading>
  'LazyCalendarNextButton': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarNextButton>
  'LazyCalendarPrevButton': LazyComponent<typeof import("../../components/ui/calendar/index").CalendarPrevButton>
  'LazyCheckbox': LazyComponent<typeof import("../../components/ui/checkbox/index").Checkbox>
  'LazyCombobox': LazyComponent<typeof import("../../components/ui/combobox/index").Combobox>
  'LazyComboboxAnchor': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxAnchor>
  'LazyComboboxEmpty': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxEmpty>
  'LazyComboboxGroup': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxGroup>
  'LazyComboboxInput': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxInput>
  'LazyComboboxItem': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxItem>
  'LazyComboboxItemIndicator': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxItemIndicator>
  'LazyComboboxList': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxList>
  'LazyComboboxSeparator': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxSeparator>
  'LazyComboboxTrigger': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxTrigger>
  'LazyComboboxViewport': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxViewport>
  'LazyDialog': LazyComponent<typeof import("../../components/ui/dialog/index").Dialog>
  'LazyDialogClose': LazyComponent<typeof import("../../components/ui/dialog/index").DialogClose>
  'LazyDialogContent': LazyComponent<typeof import("../../components/ui/dialog/index").DialogContent>
  'LazyDialogDescription': LazyComponent<typeof import("../../components/ui/dialog/index").DialogDescription>
  'LazyDialogFooter': LazyComponent<typeof import("../../components/ui/dialog/index").DialogFooter>
  'LazyDialogHeader': LazyComponent<typeof import("../../components/ui/dialog/index").DialogHeader>
  'LazyDialogOverlay': LazyComponent<typeof import("../../components/ui/dialog/index").DialogOverlay>
  'LazyDialogScrollContent': LazyComponent<typeof import("../../components/ui/dialog/index").DialogScrollContent>
  'LazyDialogTitle': LazyComponent<typeof import("../../components/ui/dialog/index").DialogTitle>
  'LazyDialogTrigger': LazyComponent<typeof import("../../components/ui/dialog/index").DialogTrigger>
  'LazyDropdownMenu': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenu>
  'LazyDropdownMenuCheckboxItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuCheckboxItem>
  'LazyDropdownMenuContent': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuContent>
  'LazyDropdownMenuGroup': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuGroup>
  'LazyDropdownMenuItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuItem>
  'LazyDropdownMenuLabel': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuLabel>
  'LazyDropdownMenuRadioGroup': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuRadioGroup>
  'LazyDropdownMenuRadioItem': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuRadioItem>
  'LazyDropdownMenuSeparator': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSeparator>
  'LazyDropdownMenuShortcut': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuShortcut>
  'LazyDropdownMenuSub': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSub>
  'LazyDropdownMenuSubContent': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSubContent>
  'LazyDropdownMenuSubTrigger': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuSubTrigger>
  'LazyDropdownMenuTrigger': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuTrigger>
  'LazyInputGroup': LazyComponent<typeof import("../../components/ui/input-group/index").InputGroup>
  'LazyInputGroupAddon': LazyComponent<typeof import("../../components/ui/input-group/index").InputGroupAddon>
  'LazyInputGroupButton': LazyComponent<typeof import("../../components/ui/input-group/index").InputGroupButton>
  'LazyInputGroupInput': LazyComponent<typeof import("../../components/ui/input-group/index").InputGroupInput>
  'LazyInputGroupText': LazyComponent<typeof import("../../components/ui/input-group/index").InputGroupText>
  'LazyInputGroupTextarea': LazyComponent<typeof import("../../components/ui/input-group/index").InputGroupTextarea>
  'LazyInput': LazyComponent<typeof import("../../components/ui/input/index").Input>
  'LazyLabel': LazyComponent<typeof import("../../components/ui/label/index").Label>
  'LazyMenubar': LazyComponent<typeof import("../../components/ui/menubar/index").Menubar>
  'LazyMenubarCheckboxItem': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarCheckboxItem>
  'LazyMenubarContent': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarContent>
  'LazyMenubarGroup': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarGroup>
  'LazyMenubarItem': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarItem>
  'LazyMenubarLabel': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarLabel>
  'LazyMenubarMenu': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarMenu>
  'LazyMenubarRadioGroup': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarRadioGroup>
  'LazyMenubarRadioItem': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarRadioItem>
  'LazyMenubarSeparator': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarSeparator>
  'LazyMenubarShortcut': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarShortcut>
  'LazyMenubarSub': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarSub>
  'LazyMenubarSubContent': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarSubContent>
  'LazyMenubarSubTrigger': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarSubTrigger>
  'LazyMenubarTrigger': LazyComponent<typeof import("../../components/ui/menubar/index").MenubarTrigger>
  'LazyNavigationMenu': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenu>
  'LazyNavigationMenuContent': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuContent>
  'LazyNavigationMenuIndicator': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuIndicator>
  'LazyNavigationMenuItem': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuItem>
  'LazyNavigationMenuLink': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuLink>
  'LazyNavigationMenuList': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuList>
  'LazyNavigationMenuTrigger': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuTrigger>
  'LazyNavigationMenuViewport': LazyComponent<typeof import("../../components/ui/navigation-menu/index").NavigationMenuViewport>
  'LazyPagination': LazyComponent<typeof import("../../components/ui/pagination/index").Pagination>
  'LazyPaginationContent': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationContent>
  'LazyPaginationEllipsis': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationEllipsis>
  'LazyPaginationFirst': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationFirst>
  'LazyPaginationItem': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationItem>
  'LazyPaginationLast': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationLast>
  'LazyPaginationNext': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationNext>
  'LazyPaginationPrevious': LazyComponent<typeof import("../../components/ui/pagination/index").PaginationPrevious>
  'LazyPopover': LazyComponent<typeof import("../../components/ui/popover/index").Popover>
  'LazyPopoverAnchor': LazyComponent<typeof import("../../components/ui/popover/index").PopoverAnchor>
  'LazyPopoverContent': LazyComponent<typeof import("../../components/ui/popover/index").PopoverContent>
  'LazyPopoverTrigger': LazyComponent<typeof import("../../components/ui/popover/index").PopoverTrigger>
  'LazySelect': LazyComponent<typeof import("../../components/ui/select/index").Select>
  'LazySelectContent': LazyComponent<typeof import("../../components/ui/select/index").SelectContent>
  'LazySelectGroup': LazyComponent<typeof import("../../components/ui/select/index").SelectGroup>
  'LazySelectItem': LazyComponent<typeof import("../../components/ui/select/index").SelectItem>
  'LazySelectItemText': LazyComponent<typeof import("../../components/ui/select/index").SelectItemText>
  'LazySelectLabel': LazyComponent<typeof import("../../components/ui/select/index").SelectLabel>
  'LazySelectScrollDownButton': LazyComponent<typeof import("../../components/ui/select/index").SelectScrollDownButton>
  'LazySelectScrollUpButton': LazyComponent<typeof import("../../components/ui/select/index").SelectScrollUpButton>
  'LazySelectSeparator': LazyComponent<typeof import("../../components/ui/select/index").SelectSeparator>
  'LazySelectTrigger': LazyComponent<typeof import("../../components/ui/select/index").SelectTrigger>
  'LazySelectValue': LazyComponent<typeof import("../../components/ui/select/index").SelectValue>
  'LazySeparator': LazyComponent<typeof import("../../components/ui/separator/index").Separator>
  'LazySheet': LazyComponent<typeof import("../../components/ui/sheet/index").Sheet>
  'LazySheetClose': LazyComponent<typeof import("../../components/ui/sheet/index").SheetClose>
  'LazySheetContent': LazyComponent<typeof import("../../components/ui/sheet/index").SheetContent>
  'LazySheetDescription': LazyComponent<typeof import("../../components/ui/sheet/index").SheetDescription>
  'LazySheetFooter': LazyComponent<typeof import("../../components/ui/sheet/index").SheetFooter>
  'LazySheetHeader': LazyComponent<typeof import("../../components/ui/sheet/index").SheetHeader>
  'LazySheetOverlay': LazyComponent<typeof import("../../components/ui/sheet/SheetOverlay.vue").default>
  'LazySheetTitle': LazyComponent<typeof import("../../components/ui/sheet/index").SheetTitle>
  'LazySheetTrigger': LazyComponent<typeof import("../../components/ui/sheet/index").SheetTrigger>
  'LazySidebar': LazyComponent<typeof import("../../components/ui/sidebar/index").Sidebar>
  'LazySidebarContent': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarContent>
  'LazySidebarFooter': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarFooter>
  'LazySidebarGroup': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarGroup>
  'LazySidebarGroupAction': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarGroupAction>
  'LazySidebarGroupContent': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarGroupContent>
  'LazySidebarGroupLabel': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarGroupLabel>
  'LazySidebarHeader': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarHeader>
  'LazySidebarInput': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarInput>
  'LazySidebarInset': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarInset>
  'LazySidebarMenu': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenu>
  'LazySidebarMenuAction': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuAction>
  'LazySidebarMenuBadge': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuBadge>
  'LazySidebarMenuButton': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuButton>
  'LazySidebarMenuButtonChild': LazyComponent<typeof import("../../components/ui/sidebar/SidebarMenuButtonChild.vue").default>
  'LazySidebarMenuItem': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuItem>
  'LazySidebarMenuSkeleton': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuSkeleton>
  'LazySidebarMenuSub': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuSub>
  'LazySidebarMenuSubButton': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuSubButton>
  'LazySidebarMenuSubItem': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarMenuSubItem>
  'LazySidebarProvider': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarProvider>
  'LazySidebarRail': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarRail>
  'LazySidebarSeparator': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarSeparator>
  'LazySidebarTrigger': LazyComponent<typeof import("../../components/ui/sidebar/index").SidebarTrigger>
  'LazySidebarUtils': LazyComponent<typeof import("../../components/ui/sidebar/utils").default>
  'LazySkeleton': LazyComponent<typeof import("../../components/ui/skeleton/index").Skeleton>
  'LazySonner': LazyComponent<typeof import("../../components/ui/sonner/Sonner.vue").default>
  'LazyStepper': LazyComponent<typeof import("../../components/ui/stepper/index").Stepper>
  'LazyStepperDescription': LazyComponent<typeof import("../../components/ui/stepper/index").StepperDescription>
  'LazyStepperIndicator': LazyComponent<typeof import("../../components/ui/stepper/index").StepperIndicator>
  'LazyStepperItem': LazyComponent<typeof import("../../components/ui/stepper/index").StepperItem>
  'LazyStepperSeparator': LazyComponent<typeof import("../../components/ui/stepper/index").StepperSeparator>
  'LazyStepperTitle': LazyComponent<typeof import("../../components/ui/stepper/index").StepperTitle>
  'LazyStepperTrigger': LazyComponent<typeof import("../../components/ui/stepper/index").StepperTrigger>
  'LazyTable': LazyComponent<typeof import("../../components/ui/table/index").Table>
  'LazyTableBody': LazyComponent<typeof import("../../components/ui/table/index").TableBody>
  'LazyTableCaption': LazyComponent<typeof import("../../components/ui/table/index").TableCaption>
  'LazyTableCell': LazyComponent<typeof import("../../components/ui/table/index").TableCell>
  'LazyTableEmpty': LazyComponent<typeof import("../../components/ui/table/index").TableEmpty>
  'LazyTableFooter': LazyComponent<typeof import("../../components/ui/table/index").TableFooter>
  'LazyTableHead': LazyComponent<typeof import("../../components/ui/table/index").TableHead>
  'LazyTableHeader': LazyComponent<typeof import("../../components/ui/table/index").TableHeader>
  'LazyTableRow': LazyComponent<typeof import("../../components/ui/table/index").TableRow>
  'LazyTableUtils': LazyComponent<typeof import("../../components/ui/table/utils").default>
  'LazyTabs': LazyComponent<typeof import("../../components/ui/tabs/index").Tabs>
  'LazyTabsContent': LazyComponent<typeof import("../../components/ui/tabs/index").TabsContent>
  'LazyTabsList': LazyComponent<typeof import("../../components/ui/tabs/index").TabsList>
  'LazyTabsTrigger': LazyComponent<typeof import("../../components/ui/tabs/index").TabsTrigger>
  'LazyTextarea': LazyComponent<typeof import("../../components/ui/textarea/index").Textarea>
  'LazyTooltip': LazyComponent<typeof import("../../components/ui/tooltip/index").Tooltip>
  'LazyTooltipContent': LazyComponent<typeof import("../../components/ui/tooltip/index").TooltipContent>
  'LazyTooltipProvider': LazyComponent<typeof import("../../components/ui/tooltip/index").TooltipProvider>
  'LazyTooltipTrigger': LazyComponent<typeof import("../../components/ui/tooltip/index").TooltipTrigger>
  'LazyAuthUser': LazyComponent<typeof import("../../components/AuthUser.vue").default>
  'LazyCountdown': LazyComponent<typeof import("../../components/Countdown.vue").default>
  'LazyDatePicker': LazyComponent<typeof import("../../components/DatePicker.vue").default>
  'LazyTiptapEditor': LazyComponent<typeof import("../../components/TiptapEditor.vue").default>
  'LazyUserInfo': LazyComponent<typeof import("../../components/UserInfo.vue").default>
  'LazyBrand': LazyComponent<typeof import("../../components/brand.vue").default>
  'LazyChart': LazyComponent<typeof import("../../components/chart.vue").default>
  'LazyIcon': LazyComponent<typeof import("../../components/icon.vue").default>
  'LazyMap': LazyComponent<typeof import("../../components/map.client.vue").default>
  'LazyPagesDashboardEventCategoryForm': LazyComponent<typeof import("../../components/pages/dashboard/event/category/Form.vue").default>
  'LazyPagesDashboardEventCategoryItem': LazyComponent<typeof import("../../components/pages/dashboard/event/category/Item.vue").default>
  'LazyPagesDashboardEventCategoryList': LazyComponent<typeof import("../../components/pages/dashboard/event/category/List.vue").default>
  'LazyPagesDashboardEventCheckpointForm': LazyComponent<typeof import("../../components/pages/dashboard/event/checkpoint/form.vue").default>
  'LazyPagesDashboardEventCheckpointList': LazyComponent<typeof import("../../components/pages/dashboard/event/checkpoint/list.vue").default>
  'LazyPagesDashboardEventDescription': LazyComponent<typeof import("../../components/pages/dashboard/event/description.vue").default>
  'LazyPagesDashboardEventGalleryForm': LazyComponent<typeof import("../../components/pages/dashboard/event/gallery/form.vue").default>
  'LazyPagesDashboardEventGalleryList': LazyComponent<typeof import("../../components/pages/dashboard/event/gallery/list.vue").default>
  'LazyPagesDashboardEventImageUpload': LazyComponent<typeof import("../../components/pages/dashboard/event/imageUpload.vue").default>
  'LazyPagesDashboardEventMapUpload': LazyComponent<typeof import("../../components/pages/dashboard/event/mapUpload.vue").default>
  'LazyPagesDashboardEventPaymentForm': LazyComponent<typeof import("../../components/pages/dashboard/event/payment/form.vue").default>
  'LazyPagesDashboardEventPaymentList': LazyComponent<typeof import("../../components/pages/dashboard/event/payment/list.vue").default>
  'LazyPagesDashboardEventRunnerItem': LazyComponent<typeof import("../../components/pages/dashboard/event/runner/RunnerItem.vue").default>
  'LazyPagesDashboardEventRunnerList': LazyComponent<typeof import("../../components/pages/dashboard/event/runner/list.vue").default>
  'LazyPagesDashboardEventSettingsList': LazyComponent<typeof import("../../components/pages/dashboard/event/settings/list.vue").default>
  'LazyPagesDashboardEventSponsorForm': LazyComponent<typeof import("../../components/pages/dashboard/event/sponsor/form.vue").default>
  'LazyPagesDashboardEventSponsorList': LazyComponent<typeof import("../../components/pages/dashboard/event/sponsor/list.vue").default>
  'LazyPagesDashboardEventStagesForm': LazyComponent<typeof import("../../components/pages/dashboard/event/stages/form.vue").default>
  'LazyPagesDashboardEventStagesList': LazyComponent<typeof import("../../components/pages/dashboard/event/stages/list.vue").default>
  'LazyPagesDashboardEventVolunteerAssignCheckpointForm': LazyComponent<typeof import("../../components/pages/dashboard/event/volunteer/AssignCheckpointForm.vue").default>
  'LazyPagesDashboardEventVolunteerList': LazyComponent<typeof import("../../components/pages/dashboard/event/volunteer/list.vue").default>
  'LazyPagesDashboardSponsorTypeForm': LazyComponent<typeof import("../../components/pages/dashboard/sponsor_type/Form.vue").default>
  'LazyPagesDashboardVolunteerEventList': LazyComponent<typeof import("../../components/pages/dashboard/volunteer/EventList.vue").default>
  'LazyPagesDashboardVolunteerRunner': LazyComponent<typeof import("../../components/pages/dashboard/volunteer/Runner.vue").default>
  'LazyPagesDefaultHomeBanner': LazyComponent<typeof import("../../components/pages/default/home/banner.vue").default>
  'LazyPagesDefaultHomeCard': LazyComponent<typeof import("../../components/pages/default/home/card.vue").default>
  'LazyPagesDefaultNewsletter': LazyComponent<typeof import("../../components/pages/default/newsletter.vue").default>
  'LazyPagesDefaultRacesRegistrationForm': LazyComponent<typeof import("../../components/pages/default/races/registrationForm.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyComboboxCancel': LazyComponent<typeof import("../../components/ui/combobox/index").ComboboxCancel>
  'LazyDropdownMenuPortal': LazyComponent<typeof import("../../components/ui/dropdown-menu/index").DropdownMenuPortal>
  'LazyToaster': LazyComponent<typeof import("../../components/ui/sonner/index").Toaster>
  'LazyAreaChart': LazyComponent<typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaChart>
  'LazyAreaStackedChart': LazyComponent<typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").AreaStackedChart>
  'LazyLineChart': LazyComponent<typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").LineChart>
  'LazyBarChart': LazyComponent<typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").BarChart>
  'LazyDonutChart': LazyComponent<typeof import("../../node_modules/nuxt-charts/dist/runtime/vue-chrts").DonutChart>
  'LazyTiptapEditorContent': LazyComponent<typeof import("@tiptap/vue-3").EditorContent>
  'LazyTiptapFloatingMenu': LazyComponent<typeof import("@tiptap/vue-3").FloatingMenu>
  'LazyTiptapBubbleMenu': LazyComponent<typeof import("@tiptap/vue-3").BubbleMenu>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
